# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "IVO.co"
email: "info@ivo.co"
description: "Valentine is a Media designer living in a world of possiblities or Adelaide, Australia. He specialises in both print and interactive design with
an interest in layouts, typography, web development and packaging design. Although he denies it he's in love with Retro Designs (Post 50's Pre 00's)."
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "http://www.ivo.co" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown


gems:
  - jekyll-paginate
  - jekyll-compose

paginate: 6
paginate_path: "blog/page:num"
